In [1]:
import sympy as sym
import numpy as np
from IPython.display import display, Math

In [2]:
x =  sym.symbols('x')

expr = 6*x**2 + 7*x - 9
ans = sym.solve(expr)
display(Math('\\text{The solution to } %s \\space \\text{is} \\space x =  %s ' %(sym.latex(expr), sym.latex(ans))))

<IPython.core.display.Math object>

In [3]:
y = sym.symbols('y')
expr = x/4 - x*y + 5
sym.solve(expr,y)

[(x + 20)/(4*x)]

In [4]:
q = sym.symbols('q')
expr = sym.Eq(3*q + 4/q + 3, 5*q + 1/q +1)
display(Math('\\text{Simplify:} \\quad %s'%(sym.latex(sym.simplify(expr)))))
display(Math('\\text{Ans:} \\quad q = %s' %(sym.latex(sym.solve(expr)))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [5]:
expr = 2*q + 3*q**2 - 5/q - 4/q**3
display(sym.simplify(expr))
display(sym.cancel(expr))

3*q**2 + 2*q - 5/q - 4/q**3

(3*q**5 + 2*q**4 - 5*q**2 - 4)/q**3

In [6]:
expr = (sym.sqrt(3) + sym.sqrt(15) * q) / (sym.sqrt(2) + sym.sqrt(10) * q)
display(expr)
display(Math(sym.latex(sym.simplify(expr))))
expr.subs(q,3).evalf()

(sqrt(15)*q + sqrt(3))/(sqrt(10)*q + sqrt(2))

<IPython.core.display.Math object>

1.22474487139159

In [7]:
x = sym.symbols('x')
term1 = (4*x + 5)
term2 = x
display(Math(sym.latex(term1*term2)))
display(Math(sym.latex(sym.expand(term1*term2))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [8]:
def f(x,y):
    expr = (4+x)*(2-y)
    for i in range(0,3):
        if x == 0:
            y = i
            display(Math('\\text{When   x=%g and y=%g,   f(x,y) = %s}'%(0,i, sym.latex((4+x)*(2-y)))))
        

In [9]:
f(0,1)


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [10]:
Fxy = (4+x)*(2-y)

for xi in range(0,3):
    for yi in range(0,3):
        print('When x=%g and y=%g, f(x,y)=%g' %(xi, yi, Fxy.subs({x:xi,y:yi})))

When x=0 and y=0, f(x,y)=8
When x=0 and y=1, f(x,y)=4
When x=0 and y=2, f(x,y)=0
When x=1 and y=0, f(x,y)=10
When x=1 and y=1, f(x,y)=5
When x=1 and y=2, f(x,y)=0
When x=2 and y=0, f(x,y)=12
When x=2 and y=1, f(x,y)=6
When x=2 and y=2, f(x,y)=0


In [11]:
A = np.array([[1,2],[3,4]])
print(A)
display(Math(sym.latex(sym.simplify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [12]:
mat = np.zeros([4,6])
mat

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
numrange = range(0,4)

for rowi in numrange:
    for coli in numrange:
        mat[rowi,coli] = (-1)**(rowi+coli)
mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [14]:
Fxy = (4+x)*(2-y)

mat = np.zeros([3,3])

for xi in range(0,3):
    for yi in range(0,3):
        mat[xi,yi] = Fxy.subs({x:xi,y:yi})
display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [44]:
Fxy = x*y

table_range = range(0,10)
mat = np.zeros([len(table_range), len(table_range)]).astype(int)

for i in table_range:
    for j in table_range:
        mat[i,j] = Fxy.subs({x:i+1,y:j+1})
display(Math(sym.latex(sym.simplify(mat))))

<IPython.core.display.Math object>

In [55]:
z,w = sym.symbols('z,w')

f1 = x*(y+z)
f2 = (3/x) + x**2 
x = w*(4-w) + (1/w**2) * (1+w)

In [60]:
f1 * f2 - f2 * f1

0

In [78]:
x,y = sym.symbols('x,y')
e1 = 2*x + x*(4-6*x) + x
e2 = -x*(2/x + 4/x**2) + (4 + x)/(4*x)
e3 = (x+3)*(x-3)*x*(1/(9*x))

In [106]:
exprs = [e1,e2,e3]

for i in range(0,len(exprs)):
    display(Math('%s \\quad \\Longleftrightarrow \\quad %s' %(sym.latex(exprs[i]), sym.latex(sym.expand(exprs[i])))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>