In [1]:
import sympy as sym
import numpy as np
from IPython.display import display, Math
sym.init_printing()
import math

In [2]:
x =  sym.symbols('x')

expr = 6*x**2 + 7*x - 9
ans = sym.solve(expr)
display(Math('\\text{The solution to } %s \\space \\text{is} \\space x =  %s ' %(sym.latex(expr), sym.latex(ans))))

<IPython.core.display.Math object>

In [3]:
y = sym.symbols('y')
expr = x/4 - x*y + 5
sym.solve(expr,y)

⎡x + 20⎤
⎢──────⎥
⎣ 4⋅x  ⎦

In [4]:
q = sym.symbols('q')
expr = sym.Eq(3*q + 4/q + 3, 5*q + 1/q +1)
display(Math('\\text{Simplify:} \\quad %s'%(sym.latex(sym.simplify(expr)))))
display(Math('\\text{Ans:} \\quad q = %s' %(sym.latex(sym.solve(expr)))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [5]:
expr = 2*q + 3*q**2 - 5/q - 4/q**3
display(sym.simplify(expr))
display(sym.cancel(expr))

   2         5   4 
3⋅q  + 2⋅q - ─ - ──
             q    3
                 q 

   5      4      2    
3⋅q  + 2⋅q  - 5⋅q  - 4
──────────────────────
           3          
          q           

In [6]:
expr = (sym.sqrt(3) + sym.sqrt(15) * q) / (sym.sqrt(2) + sym.sqrt(10) * q)
display(expr)
display(Math(sym.latex(sym.simplify(expr))))
expr.subs(q,3).evalf()

√15⋅q + √3
──────────
√10⋅q + √2

<IPython.core.display.Math object>

1.22474487139159

In [7]:
x = sym.symbols('x')
term1 = (4*x + 5)
term2 = x
display(Math(sym.latex(term1*term2)))
display(Math(sym.latex(sym.expand(term1*term2))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [8]:
def f(x,y):
    expr = (4+x)*(2-y)
    for i in range(0,3):
        if x == 0:
            y = i
            display(Math('\\text{When   x=%g and y=%g,   f(x,y) = %s}'%(0,i, sym.latex((4+x)*(2-y)))))
        

In [9]:
f(0,1)


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [10]:
Fxy = (4+x)*(2-y)

for xi in range(0,3):
    for yi in range(0,3):
        print('When x=%g and y=%g, f(x,y)=%g' %(xi, yi, Fxy.subs({x:xi,y:yi})))

When x=0 and y=0, f(x,y)=8
When x=0 and y=1, f(x,y)=4
When x=0 and y=2, f(x,y)=0
When x=1 and y=0, f(x,y)=10
When x=1 and y=1, f(x,y)=5
When x=1 and y=2, f(x,y)=0
When x=2 and y=0, f(x,y)=12
When x=2 and y=1, f(x,y)=6
When x=2 and y=2, f(x,y)=0


In [11]:
A = np.array([[1,2],[3,4]])
print(A)
display(Math(sym.latex(sym.simplify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [12]:
mat = np.zeros([4,6])
mat

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
numrange = range(0,4)

for rowi in numrange:
    for coli in numrange:
        mat[rowi,coli] = (-1)**(rowi+coli)
mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [14]:
Fxy = (4+x)*(2-y)

mat = np.zeros([3,3])

for xi in range(0,3):
    for yi in range(0,3):
        mat[xi,yi] = Fxy.subs({x:xi,y:yi})
display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [15]:
Fxy = x*y

table_range = range(0,10)
mat = np.zeros([len(table_range), len(table_range)]).astype(int)

for i in table_range:
    for j in table_range:
        mat[i,j] = Fxy.subs({x:i+1,y:j+1})
display(Math(sym.latex(sym.simplify(mat))))

<IPython.core.display.Math object>

In [16]:
z,w = sym.symbols('z,w')

f1 = x*(y+z)
f2 = (3/x) + x**2 
x = w*(4-w) + (1/w**2) * (1+w)

In [17]:
f1 * f2 - f2 * f1

0

In [18]:
x,y = sym.symbols('x,y')
e1 = 2*x + x*(4-6*x) + x
e2 = -x*(2/x + 4/x**2) + (4 + x)/(4*x)
e3 = (x+3)*(x-3)*x*(1/(9*x))

In [19]:
exprs = [e1,e2,e3]

for i in range(0,len(exprs)):
    display(Math('%s \\quad \\Longleftrightarrow \\quad %s' %(sym.latex(exprs[i]), sym.latex(sym.expand(exprs[i])))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [20]:
math.gcd(4,16)

4

In [21]:
a = 16
b = 88

fact = math.gcd(16,88)

display(Math('\\frac{%g}{%g} = \\frac{%g \\times %g}{%g \\times %g}' %(a,b,a/fact,fact,b/fact,fact)))

<IPython.core.display.Math object>

In [22]:
a,b,c = sym.symbols('a b c')
print(sym.gcd(a*c, b*c))
print(c*sym.gcd(a,b))

a = 188888888888888888888888888888888888888888
b = 1
c = 2

print(math.gcd(a*c, b*c))
print(c*math.gcd(a,b))


c
c
2
2


In [23]:
n = 10
m = 15
table_range = range(0,10)
mat = np.zeros([n, m]).astype(int) + 99
for rowi in range(0,n):
    for colj in range(0,m):
        mat[rowi,colj] = math.gcd(rowi+1,colj+1)
display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [24]:
eqn1 = 4 * x -6
eqn2 = x**2 - 9
eqn3 = sym.sin(y)
D = dict(eqsWithX = [eqn1, eqn2], eqsWithY = [eqn3])

for keyi in D:
    print(f'Solutions for equations involving {keyi[-1]}:')

    for eqi in D[keyi]:
        leftpart = sym.latex(eqi) + ' = 0'
        midpart = '\\quad \\Rightarrow \\quad ' + keyi[-1] + ' = '
        rightpart = sym.latex(sym.solve(eqi))

        display(Math(leftpart + midpart + rightpart))



Solutions for equations involving X:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

Solutions for equations involving Y:


<IPython.core.display.Math object>

In [25]:
def check_for_one(num):
    return list(sym.factorint(num).values())

def count_factor(num):
    return len(list(sym.factorint(num).values()))

def check_for_factors(num):
    return list(sym.factorint(num).keys())

In [26]:
for num in range(2,51):
    if count_factor(num) == 1 and check_for_one(num)[0] == 1:
        print(f'{num} is a prime number')
    else:
        print(f'{num} is a composite number with prime factors {check_for_factors(num)}')

2 is a prime number
3 is a prime number
4 is a composite number with prime factors [2]
5 is a prime number
6 is a composite number with prime factors [2, 3]
7 is a prime number
8 is a composite number with prime factors [2]
9 is a composite number with prime factors [3]
10 is a composite number with prime factors [2, 5]
11 is a prime number
12 is a composite number with prime factors [2, 3]
13 is a prime number
14 is a composite number with prime factors [2, 7]
15 is a composite number with prime factors [3, 5]
16 is a composite number with prime factors [2]
17 is a prime number
18 is a composite number with prime factors [2, 3]
19 is a prime number
20 is a composite number with prime factors [2, 5]
21 is a composite number with prime factors [3, 7]
22 is a composite number with prime factors [2, 11]
23 is a prime number
24 is a composite number with prime factors [2, 3]
25 is a composite number with prime factors [5]
26 is a composite number with prime factors [2, 13]
27 is a composit

In [27]:
expr = 4*x > 8
sym.solve(expr)

2 < x ∧ x < ∞

In [28]:
sym.oo > 3478687668787868768768768768768768767676767676767676767676767676

True

In [29]:
expr = (x-1)*(x+3) > 0

sym.solve(expr)

(-∞ < x ∧ x < -3) ∨ (1 < x ∧ x < ∞)

In [30]:
expr = (3*x)/2 + (4 - 5*x)/3 <= 2 - (5*(2 - x))/4
display(expr)
sym.solve(expr)

4   x   5⋅x   1
─ - ─ ≤ ─── - ─
3   6    4    2

22            
── ≤ x ∧ x < ∞
17            

In [31]:
p1 = 2*x**3 + x**2 -x
p2 = x**3 - x**4 - 4*x**2
p1 + p2

   4      3      2    
- x  + 3⋅x  - 3⋅x  - x

In [32]:
p1 = sym.Poly(2*x**3 + x**2 -x)
display(p1.eval(2))
display(p1.coeffs())

18

[2, 1, -1]

In [33]:
ps = [sym.Poly(x**2 + 2 * x), sym.Poly(-x**3 + 4*x), sym.Poly(x**5 - x**4 + x/4 + 4)]
ps[0].degree()

2

In [34]:
for p in ps:
    if p.degree()%2 == 0:
        display(sum(p.coeffs()))
    else: 
        display(len(p.coeffs()))


3

2

4

In [49]:
Fxy = 4*x**4 - 3*x**2 + x*y**2 - 9 * y**3
Gxy = -x**3 + 6*(x**2)*y + 0.8*y**3

ans_1 = sym.expand(Fxy*Gxy)
display(ans_1.subs({x:5,y:-2}))

FXY = Fxy.subs({x:5,y:-2})
GXY = Gxy.subs({x:5,y:-2})

ans_2 = FXY*GXY
display(ans_2)

-1085833.80000000

-1085833.80000000

In [91]:
fxy = (x**6 + 2*x**4 + 6*x - y) / (x**3 + 3)

for yi in range(5,16):
    ans = sym.simplify(fxy.subs({y:yi}))
    if sym.fraction(ans)[1] == 1:
        display(Math('\\text{Solution value of y} = %g'%(yi)))

<IPython.core.display.Math object>

In [124]:
exprs = [x**2 + 4*x + 3, 2*y**2 - 1, 3*y**2 + 12*y]
for i in exprs:
    if str(sym.factor(i)).find('(') != -1:
        display(Math('%s \\quad \\Leftrightarrow \\quad %s' %(sym.latex(i),sym.latex(sym.factor(i)))))
    else:
        display(Math('%s \\quad \\Leftrightarrow \\quad \\text{not factorable!}' %(sym.latex(i))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>